import React from "react";
import Head from "next/head";
import Tabs from "@/components/Tabs";
import { GetServerSideProps } from "next";
import { AxiosResponse } from "axios";
import {
  IArticle,
  ICategory,
  ICollectionResponse,
  IQuearyOptions,
} from "@/types";
import { fetchArtilces, fetchCategories } from "@/http";
import { IPagination } from "@/types";
import ArticlesList from "@/components/ArticlesList";
import { capitalizeFristLetter, debounce, makeCategory } from "@/utils";
import Pagination from "@/components/Pagination";
import { useRouter } from "next/router";

interface IPropType {
  categories: {
    items: ICategory[];
    pagnination: IPagination;
  };
  articles: {
    items: IArticle[];
    pagination: IPagination;
  };
  slug: string;
}

const category = ({ categories, articles, slug }: IPropType) => {
  const { page, pageCount } = articles.pagination;
  const router = useRouter();
  const { category: categorySlug } = router.query;
  const handleSearch = (query: string) => {
    router.push(`/category/${categorySlug}?search=${query}`);
  };

  const formatedCategory = () => {
    return slug;
  };
  return (
    <>
      <Head>
        <title>Coding Blog {formatedCategory()}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs
        categories={categories.items}
        handleOnSearch={debounce(handleSearch, 500)}
      />
      <ArticlesList articles={articles.items} />
      <Pagination
        page={page}
        pageCount={pageCount}
        redirectUrl={`/category/${categorySlug}`}
      />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const options: IQuearyOptions = {
    populate: ["author.avatar"],
    sort: ["id:desc"],
    filters: {
      category: {
        slug: query.category,
      },
    },
    pagination: {
      page: query.page ? +query.page : 1,
      pageSize: 1,
    },
  };
  if (query.search) {
    options.filters = {
      Title: { $containsi: query.search },
    };
  }
  const qs = require("qs");

  const queryString = qs.stringify(options);

  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArtilces(queryString);

  return {
    props: {
      categories: {
        items: categories.data,
        pagination: categories.meta.pagination,
      },
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination,
      },
      slug: query.category,
    },
  };
};

export default category;
