import React from "react";
import Head from "next/head";
import Tabs from "@/components/Tabs";
import { GetServerSideProps } from "next";
import { AxiosResponse } from "axios";
import { IArticle, ICategory, ICollectionResponse } from "@/types";
import { fetchArtilces, fetchCategories } from "@/http";
import { IPagination } from "@/types";
import ArticlesList from "@/components/ArticlesList";
import { capitalizeFristLetter, makeCategory } from "@/utils";

interface IPropType {
  categories: {
    items: ICategory[];
    pagnination: IPagination;
  };
  articles: {
    items: IArticle[];
    pagination: IPagination;
  };
  slug: string;
}

const category = ({ categories, articles, slug }: IPropType) => {
  const formatedCategory = () => {
    return capitalizeFristLetter(makeCategory(slug));
  };
  return (
    <>
      <Head>
        <title>Coding Blog {formatedCategory()}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories={categories.items} />
      <ArticlesList articles={articles.items} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const options = {
    populate: ["author.avatar"],
    sort: ["id:desc"],
    filters: {
      category: {
        slug: query.category,
      },
    },
  };

  const qs = require("qs");

  const queryString = qs.stringify(options);

  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArtilces(queryString);

  return {
    props: {
      categories: {
        items: categories.data,
        pagination: categories.meta.pagination,
      },
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination,
      },
      slug: query.category,
    },
  };
};

export default category;
